# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chouka.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1684, 762)
        self.ten = QtWidgets.QPushButton(Form)
        self.ten.setGeometry(QtCore.QRect(1480, 440, 181, 111))
        self.ten.setStyleSheet("background-color: rgba(108, 253, 255, 0)")
        self.ten.setText("")
        self.ten.setObjectName("ten")
        self.one = QtWidgets.QPushButton(Form)
        self.one.setGeometry(QtCore.QRect(1270, 440, 181, 111))
        self.one.setStyleSheet("background-color: rgba(108, 253, 255, 0)")
        self.one.setText("")
        self.one.setObjectName("one")
        self.onedayone = QtWidgets.QPushButton(Form)
        self.onedayone.setGeometry(QtCore.QRect(1060, 440, 181, 111))
        self.onedayone.setStyleSheet("background-color: rgba(108, 253, 255, 0)")
        self.onedayone.setText("")
        self.onedayone.setObjectName("onedayone")
        self.gemstone = QtWidgets.QLabel(Form)
        self.gemstone.setGeometry(QtCore.QRect(1540, 31, 91, 21))
        self.gemstone.setStyleSheet("background-color: rgb(255, 254, 237); ")
        self.gemstone.setText("")
        self.gemstone.setObjectName("gemstone")
        self.num = QtWidgets.QLabel(Form)
        self.num.setGeometry(QtCore.QRect(1370, 621, 54, 21))
        self.num.setStyleSheet("background-color: rgb(255, 254, 248); ")
        self.num.setText("")
        self.num.setObjectName("num")
        self.jia = QtWidgets.QPushButton(Form)
        self.jia.setGeometry(QtCore.QRect(1640, 30, 21, 23))
        self.jia.setStyleSheet("background-color: rgba(108, 253, 255, 0)")
        self.jia.setText("")
        self.jia.setObjectName("jia")
        self.label1 = QtWidgets.QLabel(Form)
        self.label1.setGeometry(QtCore.QRect(50, 140, 131, 181))
        self.label1.setStyleSheet("background-color: rgba(255, 255, 255, 0); ")
        self.label1.setText("")
        self.label1.setObjectName("label1")
        self.label6 = QtWidgets.QLabel(Form)
        self.label6.setGeometry(QtCore.QRect(50, 380, 131, 181))
        self.label6.setStyleSheet("background-color: rgba(108, 253, 255, 0)")
        self.label6.setText("")
        self.label6.setObjectName("label6")
        self.label7 = QtWidgets.QLabel(Form)
        self.label7.setGeometry(QtCore.QRect(250, 380, 131, 181))
        self.label7.setStyleSheet("background-color: rgba(108, 253, 255, 0)")
        self.label7.setText("")
        self.label7.setObjectName("label7")
        self.label2 = QtWidgets.QLabel(Form)
        self.label2.setGeometry(QtCore.QRect(250, 140, 131, 181))
        self.label2.setStyleSheet("background-color: rgba(255, 255, 255,0); ")
        self.label2.setText("")
        self.label2.setObjectName("label2")
        self.label4 = QtWidgets.QLabel(Form)
        self.label4.setGeometry(QtCore.QRect(660, 140, 131, 181))
        self.label4.setStyleSheet("background-color: rgba(255, 255, 255, 0); ")
        self.label4.setText("")
        self.label4.setObjectName("label4")
        self.label3 = QtWidgets.QLabel(Form)
        self.label3.setGeometry(QtCore.QRect(460, 140, 131, 181))
        self.label3.setStyleSheet("background-color: rgba(255, 255, 255,0); ")
        self.label3.setText("")
        self.label3.setObjectName("label3")
        self.label9 = QtWidgets.QLabel(Form)
        self.label9.setGeometry(QtCore.QRect(660, 380, 131, 181))
        self.label9.setStyleSheet("background-color: rgba(108, 253, 255, 0)")
        self.label9.setText("")
        self.label9.setObjectName("label9")
        self.label8 = QtWidgets.QLabel(Form)
        self.label8.setGeometry(QtCore.QRect(460, 380, 131, 181))
        self.label8.setStyleSheet("background-color: rgba(108, 253, 255, 0)")
        self.label8.setText("")
        self.label8.setObjectName("label8")
        self.label10 = QtWidgets.QLabel(Form)
        self.label10.setGeometry(QtCore.QRect(860, 380, 131, 181))
        self.label10.setStyleSheet("background-color: rgba(255, 255, 255, 0); ")
        self.label10.setText("")
        self.label10.setObjectName("label10")
        self.label5 = QtWidgets.QLabel(Form)
        self.label5.setGeometry(QtCore.QRect(860, 140, 131, 181))
        self.label5.setStyleSheet("background-color: rgba(255, 255, 255, 0); ")
        self.label5.setText("")
        self.label5.setObjectName("label5")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(240, 699, 601, 21))
        self.progressBar.setStyleSheet("background-color: rgba(108, 253, 255, 0)")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label1_1 = QtWidgets.QLabel(Form)
        self.label1_1.setGeometry(QtCore.QRect(50, 330, 131, 20))
        self.label1_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font-size: 16px;\n"
"text-align: center;\n"
"font-weight: bold;")
        self.label1_1.setText("")
        self.label1_1.setObjectName("label1_1")
        self.label1_2 = QtWidgets.QLabel(Form)
        self.label1_2.setGeometry(QtCore.QRect(250, 330, 131, 21))
        self.label1_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font-size: 16px;\n"
"text-align: center;\n"
"font-weight: bold;")
        self.label1_2.setText("")
        self.label1_2.setObjectName("label1_2")
        self.label1_4 = QtWidgets.QLabel(Form)
        self.label1_4.setGeometry(QtCore.QRect(660, 330, 131, 21))
        self.label1_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font-size: 16px;\n"
"text-align: center;\n"
"font-weight: bold;")
        self.label1_4.setText("")
        self.label1_4.setObjectName("label1_4")
        self.label1_3 = QtWidgets.QLabel(Form)
        self.label1_3.setGeometry(QtCore.QRect(460, 330, 131, 20))
        self.label1_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font-size: 16px;\n"
"text-align: center;\n"
"font-weight: bold;")
        self.label1_3.setText("")
        self.label1_3.setObjectName("label1_3")
        self.label1_5 = QtWidgets.QLabel(Form)
        self.label1_5.setGeometry(QtCore.QRect(860, 330, 131, 21))
        self.label1_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font-size: 16px;\n"
"text-align: center;\n"
"font-weight: bold;")
        self.label1_5.setText("")
        self.label1_5.setObjectName("label1_5")
        self.label1_10 = QtWidgets.QLabel(Form)
        self.label1_10.setGeometry(QtCore.QRect(860, 580, 131, 21))
        self.label1_10.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font-size: 16px;\n"
"text-align: center;\n"
"font-weight: bold;")
        self.label1_10.setText("")
        self.label1_10.setObjectName("label1_10")
        self.label1_6 = QtWidgets.QLabel(Form)
        self.label1_6.setGeometry(QtCore.QRect(50, 580, 131, 21))
        self.label1_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font-size: 16px;\n"
"text-align: center;\n"
"font-weight: bold;")
        self.label1_6.setText("")
        self.label1_6.setObjectName("label1_6")
        self.label1_9 = QtWidgets.QLabel(Form)
        self.label1_9.setGeometry(QtCore.QRect(660, 580, 131, 20))
        self.label1_9.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font-size: 16px;\n"
"text-align: center;\n"
"font-weight: bold;")
        self.label1_9.setText("")
        self.label1_9.setObjectName("label1_9")
        self.label1_7 = QtWidgets.QLabel(Form)
        self.label1_7.setGeometry(QtCore.QRect(250, 580, 131, 21))
        self.label1_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font-size: 16px;\n"
"text-align: center;\n"
"font-weight: bold;")
        self.label1_7.setText("")
        self.label1_7.setObjectName("label1_7")
        self.label1_8 = QtWidgets.QLabel(Form)
        self.label1_8.setGeometry(QtCore.QRect(460, 580, 131, 20))
        self.label1_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font-size: 16px;\n"
"text-align: center;\n"
"font-weight: bold;")
        self.label1_8.setText("")
        self.label1_8.setObjectName("label1_8")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 80, 291, 41))
        self.label.setStyleSheet("background-color: rgb(255, 254, 237); \n"
"font: 75 15pt \"Agency FB\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(390, 80, 51, 41))
        self.label_2.setStyleSheet("background-color: rgb(255, 254, 237); \n"
"font: 75 15pt \"Agency FB\";")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(490, 80, 161, 41))
        self.pushButton.setStyleSheet("background-color: rgb(255, 254, 237); \n"
"font: 75 \"Agency FB\";")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(220, 650, 641, 91))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;  /* 设置圆角半径为 10 像素 */")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.raise_()
        self.ten.raise_()
        self.one.raise_()
        self.onedayone.raise_()
        self.gemstone.raise_()
        self.num.raise_()
        self.jia.raise_()
        self.label1.raise_()
        self.label6.raise_()
        self.label7.raise_()
        self.label2.raise_()
        self.label4.raise_()
        self.label3.raise_()
        self.label9.raise_()
        self.label8.raise_()
        self.label10.raise_()
        self.label5.raise_()
        self.progressBar.raise_()
        self.label1_1.raise_()
        self.label1_2.raise_()
        self.label1_4.raise_()
        self.label1_3.raise_()
        self.label1_5.raise_()
        self.label1_10.raise_()
        self.label1_6.raise_()
        self.label1_9.raise_()
        self.label1_7.raise_()
        self.label1_8.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "目前拥有彩的角色数："))
        self.label_2.setText(_translate("Form", "200"))
        self.pushButton.setText(_translate("Form", "点击查看拥有角色"))
